defaults:
  is_category: true

records:
  - title: "Benefits"
  - title: "Criminal & Tickets"
  - title: "Family & Relationships"
  - title: "Housing"
  - title: "Immigration"
  - title: "Work, Credit & Consumer"
  - title: "Other issues"
  - title: "I don't know"
